version: "3.3"
services:
  database:
    image: postgres #image of database postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5433:5432" #forward port from database to the OS
    volumes:
      - ./data:/var/lib/postgresql/data:rw
    networks:
      - default
  app:
    build:
      context: . #current directory
      dockerfile: Dockerfile #use the Dockerfile called Dockerfile
    env_file:
      - .env
    environment:
      WAIT_BEFORE: 5
      WAIT_HOSTS: database:5432
    networks:
      - default
    ports:
      - "8080:8080" #forward port from my app to the OS
